### ISSUE TITLE
Update my-site to handle New Task Workflow

### ISSUE THREAD

**Issue by Pavangbhat** [Real-Dev-Squad/website-my#198]
Reference : https://github.com/Real-Dev-Squad/website-backend/issues/460

current my site
![image](https://user-images.githubusercontent.com/45538392/148403067-ec26afe3-cbaf-4412-9979-dc4891441849.png)
**Tasks :-** 
- [ ] Create a Wrapper function that will convert old task workflow to new task workflow (**active** → **IN_PROGRESS**, **unAssigned** → **AVAILABLE** and all other in **uppercase**}
- [ ] Make **Pending** and **Active** as **IN_PROGRESS** and show tasks that are in **IN_PROGRESS | BLOCKED | SMOKE_TESING**
- [ ] Show **BLOCKED**  tasks on blocked section
- [ ] Please sync with App Owner with changes and for **Pending** section
