### ISSUE TITLE
Need to open task details page from task list

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-my#552]
### Issue Description
Currently, whenever we need to update task progress we will have to first go to the [tasks](https://my.realdevsquad.com/tasks) copy the title, and then go to the status site and search the title.

### Expected Behavior
Upon clicking on the title of the task, we should be redirected to the status site.

### Current Behavior
The title is not clickable

### Screenshots

[screen-capture (1).webm](https://github.com/Real-Dev-Squad/website-my/assets/68867418/fc5106d5-a94a-4cb4-addb-5a4295ca8e3d)
### Reproducibility

 - [x] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [x] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.
