### ISSUE TITLE
Remove need to click edit button on task card, remove unnecessary popups

### ISSUE THREAD

**Issue by skv93-coder** [Real-Dev-Squad/website-my#576]
### Issue Description

- Users, need to click on the edit icon to update the progress bar  
- Unnecessary pop-ups appears on marking the progress 100%.
- Change the text of pop up that appears after marking task progress 100% from 

![Screenshot from 2024-02-16 13-37-25](https://github.com/Real-Dev-Squad/website-my/assets/68867418/9c4eb5ec-b12a-4d33-8142-7cb325fc12fb)

### Expected Behavior
This UI's are not needed as functionality regarding them is not activated

### Current Behavior
It is shown in attached pictures

### Task planning
- [ ] remove fetch task green button
- [ ]  change text of confirmation pop up which come after user tries to mark progress 100%.
- [ ]  popup with text **Task can not be assigned to users with active OOO status**  
- [ ]  day will work on enabling the edit without click

As a subtask will also scope/work on https://github.com/Real-Dev-Squad/website-my/issues/554
### Related issue 
This task does 1st subtask listed under this https://github.com/Real-Dev-Squad/website-my/issues/554
### Screenshots

![Screenshot from 2024-02-16 13-40-12](https://github.com/Real-Dev-Squad/website-my/assets/68867418/3bb86fc7-d102-457a-ad8f-deabeff5fe1e)
![Screenshot from 2024-02-16 13-39-12](https://github.com/Real-Dev-Squad/website-my/assets/68867418/f8239879-2e7c-44c6-b354-513b23e12f0c)

### Reproducibility

 - [ ] This issue is reproducible
 - [ ] This issue is not reproducible

### Steps to Reproduce
1. 
2. 

### Severity/Priority
 - [ ] Critical
 - [ ] High
 - [ ] Medium
 - [ ] Low

### Checklist

- [ ] I have read and followed the project's code of conduct.
- [ ] I have searched for similar issues before creating this one.
- [ ] I have provided all the necessary information to understand and reproduce the issue.
- [ ] I am willing to contribute to the resolution of this issue.
